# Generated by Django 4.1.2 on 2022-10-04 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Slug', models.CharField(max_length=250)),
                ('Body', models.TextField()),
                ('Publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-Publish'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-Publish'], name='Post_post_Publish_d5d13f_idx'),
        ),
    ]
