# Generated by Django 4.1.2 on 2022-10-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Slug',
            field=models.CharField(max_length=250, unique_for_date='Publish'),
        ),
    ]
